lemp_environment/django/src/gps/urls.py
from django.urls import path
from . import views

app_name = 'gps'

urlpatterns = [
    path('', views.TopPage.as_view(), name='top_page'),
    path('history/', views.GPShistory.as_view(), name='history'),
]

lemp_environment/django/src/sample_gps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gps.urls')),
]

lemp_environment/django/src/gps/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class GPS(models.Model):
    # 緯度
    latitude = models.FloatField(
        validators=[MinValueValidator(-90), MaxValueValidator(90)],
    )
    # 経度
    longitude = models.FloatField(
        validators=[MinValueValidator(-180), MaxValueValidator(-180)],
    )

    def save(self, *args, **kwargs):
        latitude = kwargs.pop('latitude', None)
        longitude = kwargs.pop('longitude', None)

        # 有効値のみ保存
        if latitude is not None and longitude is not None:
            self.latitude = float(latitude)
            self.longitude = float(longitude)
            super().save(*args, **kwargs)

lemp_environment/django/src/gps/forms.py
from django import forms
from .models import GPS
import json
import random
import os

class AjaxForm(forms.ModelForm):
    class Meta:
        model = GPS
        fields = ()

    # ajaxのレスポンスの生成
    def ajax_response(self):
        # ファイルを読み込む
        file_path = os.path.join('gps', 'gps.json')
        with open(file_path, 'r') as fin:
            inputs = json.load(fin)
        # リストに変換
        data = [value for value in inputs.values()]
        # 適当にデータを取り出す
        response = data[random.randrange(len(data))]

        return response

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance

lemp_environment/django/src/gps/views.py
from django.shortcuts import render
from django.views.generic import ListView, FormView
from django.http import JsonResponse
from .forms import AjaxForm
from .models import GPS

class TopPage(FormView):
    # テンプレートの指定
    template_name = 'gps/top_page.html'
    # formの情報
    form_class = AjaxForm
    # form成功時の遷移先
    success_url = 'top_page'

    # post受信時
    def post(self, request, *args, **kwargs):
        form = self.get_form(self.form_class)

        # formの情報が有効な場合
        if form.is_valid():
            # ajaxのリクエストの場合
            if request.is_ajax():
                # ajaxのレスポンスを取得
                data = form.ajax_response()
                # DB登録用のインスタンスを取得
                gps = form.save(commit=False)
                # 保存処理
                gps.save(latitude=data['latitude'], longitude=data['longitude'])
                response = JsonResponse(data)
            # ajax以外のリクエストの場合
            else:
                response = super().form_valid(form)
        # formの情報が無効な場合
        else:
            response = super().form_invalid()

        return response

    # get受信時に呼ばれるメソッドのオーバーライド
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # タイトルの設定
        context['title'] = 'Leaflet + OpenStreetMap'
        # 初期の位置情報の設定
        context['position'] = {'latitude': 35.4135, 'longitude': 135.0111}

        return context

class GPShistory(ListView):
    model = GPS
    context_object_name = 'gps_histories'
    template_name = 'gps/history.html'
    paginate_by = 20

lemp_environment/django/src/templates/base.html
<!doctype html>
<html lang="ja">
<head>
    {# Required meta tags #}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% block header %}
    {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}
    {% block scripts %}
    {% endblock %}
</body>

</html>

lemp_environment/django/src/templates/gps/history.html
{% extends "base.html" %}

{% block title %}
GPS history
{% endblock %}

{% block header %}
{# Bootstrap CSS #}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
      integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
{% endblock %}

{% block content %}
<div class="container mt-3">
    <div class="row  justify-content-center">
        <div class="col-12">
            <div class="row">
                <div class="col-8">
                    <h3>history</h3>
                </div>
                <div class="col-4">
                    <a href="{% url 'gps:top_page' %}" class="btn btn-outline-primary btn-md btn-block">トップページへ戻る</a>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th>緯度</th>
                                <th>経度</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for gps in gps_histories %}
                            <tr>
                                <td scope="row">{{ gps.id }}</td>
                                <td scope="row">{{ gps.latitude }}</td>
                                <td scope="row">{{ gps.longitude }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    {% include 'pagination.html' %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{# jQuery first, then Popper.js, then Bootstrap JS #}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
{% endblock %}

lemp_environment/django/src/templates/gps/top_page.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
        crossorigin=""/>
    {# Make sure you put this AFTER Leaflet's CSS #}
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>
    {# jQuery #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <style>
        #mapid {
            width: 40%;
            height: 512px;
        }
    </style>
{% endblock %}

{% block content %}
<div>
    <h3> Leaflet + OpenStreetMap </h3>
    <div>
        {# formの定義 #}
        <form action="", method="post">
            {% csrf_token %}
            {{ form }}
            <button>位置情報の取得（ajax）</button>
        </form>
    </div>
    <div>
        {# ajaxの取得結果（初回読み込み時のみ、get_context_dataの値） #}
        <p id="result_ajax">({{ position.latitude }}, {{ position.longitude }})</p>
    </div>
    <div>
        <a href="{% url 'gps:history' %}" target="_self">GPS受信履歴の確認</a>
    </div>

    <div id="mapid"></div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(function () {
        let map;
        let tile_layer;

        // ボタン押下時の処理
        $('form').submit(function(event) {
            event.preventDefault();
            const form = $(this);

            // サーバ側にGPS情報を取得するように依頼
            $.ajax({
                url: form.prop('action'),   // アクセスするURL
                type: form.prop('method'),  // post or get
                cache: false,               // cacheの利用有無
                dataType: 'json',           // data type (script, json, htmlなど)
                data: form.serialize(),     // 送るデータ
            })
            .done(function (response) {
                // 緯度・経度の取得
                const latitude = response.latitude;
                const longitude = response.longitude;
                // 表示位置を変更
                map.panTo([latitude, longitude]);
                // マーカーの移動
                L.marker([latitude, longitude]).addTo(map);
                $('#result_ajax').text(`(${latitude}, ${longitude})`);
            })
            .fail(function (response) {
                $('#result_ajax').text('Failed');
            });
        });

        // 初期化関数
        const init = () => {
            // mapの生成
            const latitude = {{ position.latitude }};
            const longitude = {{ position.longitude }};
            map = L.map('mapid', {
                center: [latitude, longitude],
                zoom: 17,
            });
            // tileの取得
            tile_layer = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: 'c <a href="http://osm.org/copyright">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
            });
            tile_layer.addTo(map);
            // マーカー画像の場所を指定
            L.marker([latitude, longitude]).addTo(map);
        };
        $(init);
    });
</script>
{% endblock %}

lemp_environment/django/src/templates/pagination.html
<nav aria-label="Page navigation example">

    <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

</nav>